image: node:16-alpine3.14

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

sign-task:
  only:
    - schedules
  script:
    - npm install
    - node ./index.mjs

